version: '2'
services:
  user-service:
    image: cloudestimator/user-service:${BUILD_NAME}
    mem_limit: 1000000000
    ports:
       - "8081:8081"
    environment:
       EUREKASERVER_URI:  "http://ip-172-31-6-126.us-west-2.compute.internal:8761/eureka/"
       CONFIGSERVER_URI:  "http://ip-172-31-0-104.us-west-2.compute.internal:8888"
       PROFILE:           "prod"