version: '2'
services:
  user-service:
    image: cloudestimator/user-service:${BUILD_NAME}
    mem_limit: 1000000000
    ports:
       - "8081:8081"
    environment:
       EUREKASERVER_URI:  "http://internal-cloud-estimator-lb-1078220646.us-west-2.elb.amazonaws.com:8761/eureka/"
       CONFIGSERVER_URI:  "http://internal-cloud-estimator-lb-1078220646.us-west-2.elb.amazonaws.com:8888"
       PROFILE:           "prod"
       ENCRYPT_KEY:       "f3831f8cc338"